### ISSUE TITLE
Can't get any data

### ISSUE THREAD

**Issue by yoavaya** [matthewtckr/pdi-zendesk-plugin#42]
While trying to get data from Zendesk through the Zendesk input. I'm getting the following error messages: 
`2018/02/20 09:43:22 - Zendesk Input Organizations.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : Unexpected error
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - ERROR (version 8.0.0.0-28, build 8.0.0.0-28 from 2017-11-05 07.27.50 by buildguy) : org.zendesk.client.v2.ZendeskResponseException: HTTP/401: Unauthorized
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2130)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:91)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2336)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.pentaho.di.trans.steps.zendesk.ZendeskFacade$ZendeskIterable$ZendeskIterator.hasNext(ZendeskFacade.java:388)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.pentaho.di.trans.steps.zendesk.ZendeskInputOrganizations.processRow(ZendeskInputOrganizations.java:126)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at java.lang.Thread.run(Unknown Source)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - Caused by: org.zendesk.client.v2.ZendeskResponseException: HTTP/401: Unauthorized
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:1946)
2018/02/20 09:43:22 - Zendesk Input Organizations.0 - 	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:1924)`

As I see it. There is an issue with the authentication. I'm using the same credentials while connecting directly to the Zendesk portal successfully. 

What do I missed?

**Comment by matthewtckr** [comment]
Hi @yoavaya,

If you're logged into the Zendesk portal in your web browser, what happens if you navigate to `https://<subdomain>.zendesk.com/api/v2/tickets/recent.json`?  If the REST API is enabled and you have sufficient permissions with your Zendesk account, you should see a JSON response.  If it does return a JSON response, I'd recommend reviewing your subdomain and credentials settings in the step.

If I remember correctly, the REST API can be enabled under the Admin tab, in `Channels > API`.  You might need to contact Zendesk Support in case you run into any issues, as I can't find a quick article for you from Zendesk that guides you through the setup process.

Hope that helps!
